---
#Create Repo if OS is red hat
- name: insall EPEL 6.8 repository
  shell: /bin/rpm -ivh http://download.fedoraproject.org/pub/epel/6/i386/epel-release-6-8.noarch.rpm creates=/etc/yum.repos.d/epel.repo
  tags: 
    - never
    - epel
- name: enable EPEL repo
  ini_file: dest=/etc/yum.repos.d/epel.repo
            section=epel
            option=enabled
            value=1
  tags:
    - never 
    - epel

# Install mysql Packages
- name: Install the MySQL packages
  package:
         name: "{{ item }}"
         state: present
         update_cache: "{{ UPDATE_PACKAGE_MANAGER }}"
  with_items: 
    - "{{ MYSQL_PACKAGE_MANAGER }}"
    - "{{ MYSQL_PACKAGE_INSTALLATION }}"
  notify:
    - start-mysql

#Copy the query
- name: copy the query
  template:
    src: "query.yaml"
    dest: "{{ MYSQL_SETUP_DIR }}/query.sql" 

# Copy the db_scripts
- name: Copy the db script
  copy:
          src: "create_db.sh"
          dest: "{{ MYSQL_SETUP_DIR }}"
          mode: "0755"

#Run the Database Script
- name: run the query
  shell: "./create_db.sh {{ MYSQL_ROOT_USER }} {{ MYSQL_ROOT_PASSWORD }} {{ MYSQL_SETUP_DIR }}/query.sql"
  args:
      chdir: "{{ MYSQL_SETUP_DIR }}"
  register: db_creation_out

- debug: 
    msg: "db_creation is successfull."
  when: db_creation_out.rc == 0

- debug: 
    msg: "dbcreation unsuccessfull"
  when: db_creation_out.rc == 1
